### ISSUE TITLE
Extension crashes extension manager in TYPO3 6.2.17

### ISSUE THREAD

**Issue by chris246** [punktDe/pt_extlist#10]
> Version number in composer manifest of package "pt_extlist" is missing or invalid
> More information regarding this error might be available [online](http://typo3.org/go/exception/CMS/1395614959).

Renaming the composer.json file or deleting is a dirty fix...

**Comment by daniellienert** [comment]
This seems to be a issue with the TYPO3 6.2 extension manager. See https://wiki.typo3.org/Exception/CMS/1395614959. I haven't found a solution to have the composer install ability and to avoid this error. 

I would recommend to use an older version of pt_extlist or update your TYPO3 installation.

Cheers,
Daniel

**Comment by chris246** [comment]
Hi Daniel,

I use an older version of extlist for now, as the current TYPO3 7 version is unusable from my point of view: https://forge.typo3.org/issues/71494

Thank you for your help
Christoph
