### ISSUE TITLE
Updating pt_extlist to 2.2.0 crashes pages with yag

### ISSUE THREAD

**Issue by chris246** [punktDe/pt_extlist#11]
PHP Fatal error:  Call to undefined method Tx_PtExtlist_Domain_Configuration_Filters_FilterConfig::configValueExistsAndNotNothing() in [...]/typo3/typo3conf/ext/pt_extlist/Classes/Domain/Configuration/Filters/FilterConfig.php on line 336

Caches cleared via install tool Important actions > Clear all cache

Maybe related to #9?

**Comment by daniellienert** [comment]
Please make sure, that you have the latest version of pt_extlist, yag and pt_extbase

**Comment by chris246** [comment]
As I'm still using TYPO3 6 (see #10), the latest updates for yag and pt_extbase weren't suggested in the extension manager. Just the one for pt_extlist which then crashed pages with yag.
Maybe you want to set the TYPO3 dependency to 7.x, as in the other plugins, also as the composer.json #10 breaks the extension manager of TYPO3 6 (and is therefore not compatible to TYPO3 6).

**Comment by daniellienert** [comment]
Thanks for the hint. I changed the minimum version.

**Comment by liayn** [comment]
Just for info. TER of course still offers the 2.2.0 version for CMS 6.2. I suggest to release a 2.2.1, which is for 6.2 and which fixes the issue and then release a 3.0.0 for CMS 7+ only.

**Comment by hocomadvies** [comment]
Hi, I updated today and experience the same problem. in Typo3 6.2.19 with version 2.2.2 ? Tried to reverse to a lower version but that did non work either. How to get this - YAG Gallery page - working again?

**Comment by liayn** [comment]
@hocomadvies Remove downgrade one version and make sure you cleared all caches via Install Tool.

**Comment by liayn** [comment]
@daniellienert Would be nice if you could follow my suggestion from above. Release one last version for 6.2 that works and has a version number higher than 2.2.1, otherwise people have to remember not to update this ext each time.

**Comment by liayn** [comment]
@daniellienert Repeating my request, please get a fixed version out for 6.2.x!!!

Forge issue is: https://forge.typo3.org/issues/73515

**Comment by TobiLei** [comment]
Hi all,

for Typo3 6.2 you must use the following versions:

- Core: 6.2.xx (in the moment 6.2.31)
- pt_extbase: 2.1.0
- pt_extlist: 2.0.4
- yag: 4.0.7
- yag_themepack_jquery: 1.3.1

Please ignore any updates for this extensions.

TobiLei
