### ISSUE TITLE
error under php7

### ISSUE THREAD

**Issue by EnzephaloN** [punktDe/pt_extlist#13]
For tests I switched to php7.
Got the following error:

`PHP Warning: Declaration of Tx_PtExtlist_Domain_Model_Filter_FilterFactory::injectObjectManager(TYPO3\CMS\Extbase\Object\ObjectManagerInterface $objectManager) should be compatible with Tx_PtExtlist_Domain_AbstractComponentFactory::injectObjectManager(TYPO3\CMS\Extbase\Object\ObjectManager $objectManager) in /home/www/weimarhalle.de/typo3conf/ext/pt_extlist/Classes/Domain/Model/Filter/FilterFactory.php line 38`

and

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class Tx_PtExtlist_Domain_Model_Filter_FilterFactory does not exist

Do you know how to fix?

**Comment by lisandi** [comment]
we get the same warning and Yag Gallery won't work under PHP7

**Comment by FaraFara** [comment]
I am submit this issue to
