### ISSUE TITLE
wrong call of configValueExiststAndNotNothing

### ISSUE THREAD

**Issue by EnzephaloN** [punktDe/pt_extlist#9]
Hello
In Classes/Domain/Configuration/Filters/FilterConfig.php at row 338ff there are two incorrect callings of configValueExists**t**AndNotNothing from pt_extbase.

The correct name must be configValueExists**t**AndNotNothing instead of configValueExistsAndNotNothing

Best regards
Johannes

**Comment by daniellienert** [comment]
Hey Johannes, 

sorry, but my config is correct - and I am sure, that our automatic tests would have found such an error ... 
Please have a look into https://github.com/punktDe/pt_extlist/blob/master/Classes/Domain/Configuration/Filters/FilterConfig.php and compare it with your local version.

Cheers,
Daniel

**Comment by EnzephaloN** [comment]
Hello
There was an pt_extbase version 2.1.1 and there the method was called configValueExiststAndNotNothing. And also in pt_extlist 2.0.4 the call was on configValueExiststAndNotNothing. 
If you use new pt_extlist with old pt_extbase you run into this error.

http://www.weimarhalle.de/fileadmin/download/extlist_extbase_Existst.jpg
